on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

name: CI

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [lints, docs]
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
        rust:
          - stable
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

      - name: Install cross toolchain
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --workspace --exclude zephyr-mcumgr-python

      - name: Test
        run: cargo test --release --workspace --exclude zephyr-mcumgr-python --verbose $DOCTEST_XCOMPILE -- --test-threads 1

  build-examples:
    name: Build Examples
    runs-on: ubuntu-latest
    needs: [lints, docs]
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --examples --all-features --release

  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    needs: [lints, docs]
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-msrv
        run: cargo binstall --version 0.18.4 --no-confirm cargo-msrv

      - name: Check MSRV of zephyr-mcumgr
        run: cargo msrv verify --path zephyr-mcumgr --log-target=stdout --output-format=json

      - name: Check MSRV of zephyr-mcumgr-cli
        run: cargo msrv verify --path zephyr-mcumgr-cli --log-target=stdout --output-format=json

  semver:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    needs: [lints, docs]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: zephyr-mcumgr/Cargo.toml

  # min-versions:
  #   name: Minimal Dependency Versions
  #   runs-on: ubuntu-latest
  #   needs: [lints, docs]
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v5

  #     - name: Install dependencies
  #       run: sudo apt-get install -y libudev-dev

  #     - name: Install nightly toolchain
  #       uses: dtolnay/rust-toolchain@nightly

  #     - name: Install cargo-hack
  #       uses: taiki-e/install-action@cargo-hack
  #     - name: Install cargo-minimal-versions
  #       uses: taiki-e/install-action@cargo-minimal-versions

  #     - name: Check with minimal versions
  #       run: cargo minimal-versions check --workspace --ignore-private

  # min-versions-msrv:
  #   name: Minimal Dependency Versions (MSRV)
  #   runs-on: ubuntu-latest
  #   needs: [lints, docs]
  #   env:
  #     RUSTFLAGS: "-D warnings"
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v5

  #     - name: Install dependencies
  #       run: sudo apt-get install -y libudev-dev

  #     - name: Install nightly toolchain
  #       uses: dtolnay/rust-toolchain@nightly

  #     - name: Install cargo-binstall
  #       uses: taiki-e/install-action@cargo-binstall
  #     - name: Install cargo-msrv
  #       run: cargo binstall --version 0.18.4 --no-confirm cargo-msrv
  #     - name: Install cargo-hack
  #       uses: taiki-e/install-action@cargo-hack
  #     - name: Install cargo-minimal-versions
  #       uses: taiki-e/install-action@cargo-minimal-versions

  #     - name: Determine MSRV
  #       run: echo "MSRV=$(cargo msrv --path zephyr-mcumgr show --output-format=minimal)" >> $GITHUB_ENV

  #     - name: Show MSRV
  #       run: echo "$MSRV"

  #     - name: Install MSRV Rust version
  #       run: rustup toolchain install "$MSRV"

  #     - name: Check with minimal versions
  #       run: cargo "+$MSRV" minimal-versions check --workspace --ignore-private

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo doc
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        run: cargo doc --no-deps

  leaks:
    name: Memory leaks
    runs-on: ubuntu-latest
    needs: [lints, docs]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        # llvm required to resolve symbols in sanitizer output
        run: sudo apt-get install -y libudev-dev llvm

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        env:
          RUSTFLAGS: "-Z sanitizer=address"
        run: cargo build --target x86_64-unknown-linux-gnu --tests

      - name: Run tests with leak sanitizer
        env:
          RUSTFLAGS: "-Z sanitizer=address"
        run: cargo test
          --target x86_64-unknown-linux-gnu --tests
          -- --test-threads 1

  release:
    name: Publish version
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'release'
    needs: [
        test,
        build-examples,
        msrv,
        lints,
        docs,
        leaks,
        semver,
        # min-versions,
        # min-versions-msrv,
      ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Query crate version
        run: echo "lib_crate_version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: Query crate version
        run: echo "cli_crate_version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[1].version')" >> $GITHUB_ENV

      - name: Query release tag version
        run: echo "release_tag_version=${{ github.event.release.name }}" >> $GITHUB_ENV

      - name: Print versions
        run: echo "Lib Crate - ${{ env.lib_crate_version }}, CLI Crate - ${{ env.cli_crate_version }}, Release - ${{ env.release_tag_version }}"

      - name: Check lib version not empty
        run: test -n "${{ env.lib_crate_version }}"

      - name: Check cli version not empty
        run: test -n "${{ env.cli_crate_version }}"

      - name: Check matching version for lib
        run: test "${{ env.lib_crate_version }}" = "${{ env.release_tag_version }}"

      - name: Check matching version for cli
        run: test "${{ env.cli_crate_version }}" = "${{ env.release_tag_version }}"

      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Cargo publish
        run: cargo publish --workspace
